# **Title & Objective**

# 🧹 Data Cleaning & Transformation
## Objective

The objective of this notebook is to clean and transform the Superstore sales dataset and prepare it for Exploratory Data Analysis (EDA).

The notebook focuses on data cleaning, data manipulation, and feature creation using Pandas and NumPy.

# **Data Preparation Steps**

## Data Preparation Steps

1. Load the dataset
2. Convert date columns
3. Clean text data
4. Validate important values
5. Create useful analytical features
6. Prepare the final dataset for EDA

# **Import Libraries**

In [4]:
import pandas as pd
import numpy as np

# **Mount Google Drive**

In [5]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

# **Load Dataset**

In [6]:
file_path = "/content/drive/MyDrive/Sales_Performance_Analytics/data/Superstore.csv"

df = pd.read_csv(file_path, encoding="latin1")

# **Create Working Copy**

In [7]:
cleaned_df = df.copy()

# **Convert Date Columns**

In [8]:
cleaned_df['Order Date'] = pd.to_datetime(cleaned_df['Order Date'])
cleaned_df['Ship Date'] = pd.to_datetime(cleaned_df['Ship Date'])

In [9]:
cleaned_df[['Order Date', 'Ship Date']].dtypes

Order Date    datetime64[ns]
Ship Date     datetime64[ns]
dtype: object

# **Create Shipping Days**

In [10]:
cleaned_df['Shipping Days'] = (
    cleaned_df['Ship Date'] - cleaned_df['Order Date']
).dt.days

In [11]:
cleaned_df[['Order Date', 'Ship Date', 'Shipping Days']].head()

  Order Date  Ship Date  Shipping Days
0 2016-11-08 2016-11-11              3
1 2016-11-08 2016-11-11              3
2 2016-06-12 2016-06-16              4
3 2015-10-11 2015-10-18              7
4 2015-10-11 2015-10-18              7

# **Create Date Features**

In [12]:
cleaned_df['Order Year'] = cleaned_df['Order Date'].dt.year
cleaned_df['Order Month'] = cleaned_df['Order Date'].dt.month
cleaned_df['Order Month Name'] = cleaned_df['Order Date'].dt.month_name()

In [13]:
cleaned_df[['Order Date', 'Order Year', 'Order Month', 'Order Month Name']].head()

  Order Date  Order Year  Order Month Order Month Name
0 2016-11-08        2016           11         November
1 2016-11-08        2016           11         November
2 2016-06-12        2016            6             June
3 2015-10-11        2015           10          October
4 2015-10-11        2015           10          October

# **Text Data Cleaning**

In [14]:
text_columns = [
    'Order ID',
    'Ship Mode',
    'Customer ID',
    'Customer Name',
    'Segment',
    'Country',
    'City',
    'State',
    'Region',
    'Product ID',
    'Category',
    'Sub-Category',
    'Product Name'
]

In [15]:
for col in text_columns:
    cleaned_df[col] = cleaned_df[col].str.strip()

# **Verify Text Cleaning**

In [21]:
cleaned_df[text_columns].head()

,Order ID,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Region,Product ID,Category,Sub-Category,Product Name
0,CA-2016-152156,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase
1,CA-2016-152156,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,..."
2,CA-2016-138688,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...
3,US-2015-108966,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table
4,US-2015-108966,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System

# **Final Dataset Columns Check**

In [17]:
cleaned_df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit',
       'Shipping Days', 'Order Year', 'Order Month', 'Order Month Name'],
      dtype='object')

# **Final Dataset Check**

In [18]:
cleaned_df.shape

(9994, 25)

In [19]:
cleaned_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Row ID            9994 non-null   int64
 1   Order ID          9994 non-null   object
 2   Order Date        9994 non-null   datetime64[ns]
 3   Ship Date         9994 non-null   datetime64[ns]
 4   Ship Mode         9994 non-null   object
 5   Customer ID       9994 non-null   object
 6   Customer Name     9994 non-null   object
 7   Segment           9994 non-null   object
 8   Country           9994 non-null   object
 9   City              9994 non-null   object
 10  State             9994 non-null   object
 11  Postal Code       9994 non-null   int64
 12  Region            9994 non-null   object
 13  Product ID        9994 non-null   object
 14  Category          9994 non-null   object
 15  Sub-Category      9994 non-null   object
 16  Product Name      9994 non-null   object
 17  Sales             9994 non-null   float64
 18  Quantity          9994 non-null   int64
 19  Discount          9994 non-null   float64
 20  Profit            9994 non-null   float64
 21  Shipping Days     9994 non-null   int64
 22  Order Year        9994 non-null   int32
 23  Order Month       9994 non-null   int32
 24  Order Month Name  9994 non-null   object
dtypes: datetime64[ns](2), float64(3), int32(2), int64(4), object(14)
memory usage: 1.8+ MB

# **Final Preview**

In [20]:
cleaned_df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Days,Order Year,Order Month,Order Month Name
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,3,2016,11,November
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,3,2016,11,November
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,4,2016,6,June
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,7,2015,10,October
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,7,2015,10,October

# **Cleaning Summary**

## Cleaning & Transformation Summary

The following data preparation tasks were completed:

- Converted `Order Date` and `Ship Date` into datetime format.
- Created `Shipping Days` to measure delivery duration.
- Created `Order Year` for yearly analysis.
- Created `Order Month` for monthly analysis.
- Created `Order Month Name` for readable monthly analysis.
- Removed leading and trailing spaces from relevant text columns.
- Preserved the original dataset by working on a separate DataFrame.

The transformed dataset is now ready for Exploratory Data Analysis (EDA).